[tool.black]
line-length = 125
skip-string-normalization = true
force-exclude = "LICENSE|.+.sql|.+.json|.+.md|.+.yml|.+.env|.+.txt"

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 100
